Rails:
  Enabled: true

AllCops:
  Exclude:
  - 'db/**/*'
  - 'config/**/*'
  - 'script/**/*'
  - 'bin/**'
  - 'spec/spec_helper.rb'
  - 'spec/rails_helper.rb'
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
  - 'app/**/*'
  - 'spec/**/*'